variable app_service  {}
variable location_dev{}
variable rg_dev{}
variable asp_id{}
variable acr_url{}
variable acr_username{}
variable acr_password{}
variable connect_basic_auth_credentials_source{}
variable connect_basic_auth_user_info{}
variable connect_bootstrap_servers{}
variable connect_config_storage_topic{}
variable connect_consumer_sasl_jaas_config{}
variable connect_consumer_sasl_mechanism{}
variable connect_consumer_sasl_password{}
variable connect_consumer_sasl_username{}
variable connect_consumer_security_protocol{}
variable connect_group_id{}
variable connect_key_converter{}
variable connect_offset_storage_topic{}
variable connect_plugin_path{}
variable connect_producer_sasl_jaas_config{}
variable connect_producer_sasl_mechanism{}
variable connect_producer_sasl_password{}
variable connect_producer_sasl_username{}
variable connect_producer_security_protocol{}
variable connect_rest_advertised_host_name{}
variable connect_sasl_jaas_config{}
variable connect_sasl_mechanism{}
variable connect_sasl_password{}
variable connect_sasl_username{}
variable connect_schema_registry_url{}
variable connect_security_protocol{}
variable connect_status_storage_topic{}
variable connect_value_converter{}
variable website_httplogging_retention_days{}
variable websites_enable_app_service_storage{}
