apiVersion: v1
kind: Service
metadata:
  name: tpg-input-streams-service
  namespace: dev-tpg
spec:
  selector:
    app: tpg-input-streams
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpg-input-streams-deploy
  namespace: dev-tpg
spec:
  selector:
    matchLabels:
      app: tpg-input-streams
  replicas: 1
  template:
    metadata:
      labels:
        app: tpg-input-streams
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        stdin: true
        tty: true
        env:
          - name : spring.app.name
            value: Tap-TpgInput-Streams
        ports:
          - containerPort: 8000